class_name KeyIconMap


static var playstation_keys: Dictionary = {
	"0"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_button_color_cross.png",
	"1"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_button_color_circle.png",
	"2"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_button_color_square.png",
	"3"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_button_color_triangle.png",
	"4"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation5_button_create.png",
	"6"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation5_button_options.png",
	"7"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_stick_side_l.png",
	"8"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_stick_side_r.png",
	"9"       = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_trigger_l1_alternative.png",
	"10"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_trigger_r1_alternative.png",
	"11"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_dpad_up.png",
	"12"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_dpad_down.png",
	"13"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_dpad_left.png",
	"14"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation_dpad_right.png",
	"15"      = "res://UI/Keybinding/KennyControllerPrompts/Playstation/playstation5_button_mute.png",
}


static var xbox_series_keys: Dictionary = {
	"0"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_a_outline.png",
	"1"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_b_outline.png",
	"2"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_x_outline.png",
	"3"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_y_outline.png",
	"4"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_view_outline.png",
	"5"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_guide.png",
	"6"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_menu_outline.png",
	"7"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_stick_side_l.png",
	"8"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_stick_side_r.png",
	"9"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_lb_outline.png",
	"10"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_rb_outline.png",
	"11"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_up_outline.png",
	"12"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_down_outline.png",
	"13"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_left_outline.png",
	"14"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_right_outline.png",
	"15"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_share_outline.png",
}


static var xbox_360_keys: Dictionary = {
	"0"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_color_a.png",
	"1"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_color_b.png",
	"2"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_color_x.png",
	"3"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_color_y.png",
	"4"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_back.png",
	"5"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_guide_outline.png",
	"6"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_button_start.png",
	"7"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_stick_side_l.png",
	"8"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_stick_side_r.png",
	"9"       = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_lb.png",
	"10"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_rb.png",
	"11"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_round_up.png",
	"12"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_round_down.png",
	"13"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_round_left.png",
	"14"      = "res://UI/Keybinding/KennyControllerPrompts/Xbox/xbox_dpad_round_right.png",
}


static var keys: Dictionary = {
	"48"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/0_Key_Light.png",
	"49"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/1_Key_Light.png",
	"50"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/2_Key_Light.png",
	"51"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/3_Key_Light.png",
	"52"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/4_Key_Light.png",
	"53"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/5_Key_Light.png",
	"54"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/6_Key_Light.png",
	"55"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/7_Key_Light.png",
	"56"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/8_Key_Light.png",
	"57"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/9_Key_Light.png",
	"65"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/A_Key_Light.png",
	"66"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/B_Key_Light.png",
	"67"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/C_Key_Light.png",
	"68"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/D_Key_Light.png",
	"69"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/E_Key_Light.png",
	"70"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F_Key_Light.png",
	"71"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/G_Key_Light.png",
	"72"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/H_Key_Light.png",
	"73"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/I_Key_Light.png",
	"74"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/J_Key_Light.png",
	"75"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/K_Key_Light.png",
	"76"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/L_Key_Light.png",
	"77"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/M_Key_Light.png",
	"78"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/N_Key_Light.png",
	"79"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/O_Key_Light.png",
	"80"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/P_Key_Light.png",
	"81"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Q_Key_Light.png",
	"82"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/R_Key_Light.png",
	"83"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/S_Key_Light.png",
	"84"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/T_Key_Light.png",
	"85"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/U_Key_Light.png",
	"86"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/V_Key_Light.png",
	"87"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/W_Key_Light.png",
	"88"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/X_Key_Light.png",
	"89"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Y_Key_Light.png",
	"90"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Z_Key_Light.png",
	"4194328" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Alt_Key_Light.png",
	"4194322" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Arrow_Down_Key_Light.png",
	"4194319" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Arrow_Left_Key_Light.png",
	"4194321" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Arrow_Right_Key_Light.png",
	"4194320" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Arrow_Up_Key_Light.png",
	"42"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Asterisk_Key_Light.png",
	"4194433" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Asterisk_Key_Light.png",
	"4194308" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Backspace_Alt_Key_Light.png",
	"91"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Bracket_Left_Key_Light.png",
	"93"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Bracket_Right_Key_Light.png",
	"4194329" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Caps_Lock_Key_Light.png",
	"4194327" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Command_Key_Light.png",
	"4194326" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Ctrl_Key_Light.png",
	"4194312" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Del_Key_Light.png",
	"4194318" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/End_Key_Light.png",
	"4194309" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Enter_Alt_Key_Light.png",
	"4194305" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Esc_Key_Light.png",
	"4194332" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F1_Key_Light.png",
	"4194333" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F2_Key_Light.png",
	"4194334" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F3_Key_Light.png",
	"4194335" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F4_Key_Light.png",
	"4194336" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F5_Key_Light.png",
	"4194337" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F6_Key_Light.png",
	"4194338" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F7_Key_Light.png",
	"4194339" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F8_Key_Light.png",
	"4194340" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F9_Key_Light.png",
	"4194341" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F10_Key_Light.png",
	"4194342" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F11_Key_Light.png",
	"4194343" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/F12_Key_Light.png",
	"4194317" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Home_Key_Light.png",
	"4194311" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Insert_Key_Light.png",
	"60"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Mark_Left_Key_Light.png",
	"62"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Mark_Right_Key_Light.png",
	"45"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Minus_Key_Light.png",
	"4194435" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Minus_Key_Light.png",
	"4194330" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Num_Lock_Key_Light.png",
	"4194324" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Page_Down_Key_Light.png",
	"4194323" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Page_Up_Key_Light.png",
	"43"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Plus_Key_Light.png",
	"4194437" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Plus_Key_Light.png",
	"4194314" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Print_Screen_Key_Light.png",
	"63"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Question_Key_Light.png",
	"34"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Quote_Key_Light.png",
	"59"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Semicolon_Key_Light.png",
	"4194325" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Shift_Key_Light.png",
	"47"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Slash_Key_Light.png",
	"4194434" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Slash_Key_Light.png",
	"32"      = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Space_Key_Light.png",
	"4194306" = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Tab_Key_Light.png",
	"126"     = "res://UI/Keybinding/XeluController&KeyPrompts/Keyboard & Mouse/Light/Tilda_Key_Light.png",
}

static var mouse_buttons: Dictionary = {
	"1"       = "res://UI/Keybinding/KennyControllerPrompts/Mouse/mouse_left.png",
	"3"       = "res://UI/Keybinding/KennyControllerPrompts/Mouse/mouse_scroll.png",
	"2"       = "res://UI/Keybinding/KennyControllerPrompts/Mouse/mouse_right.png",
	"4"       = "res://UI/Keybinding/KennyControllerPrompts/Mouse/mouse_scroll_up.png",
	"5"       = "res://UI/Keybinding/KennyControllerPrompts/Mouse/mouse_scroll_down.png",
}
